# benim için gemini ai dan şablon istedim

import pandas as pd
import random
from faker import Faker
from datetime import datetime, timedelta

# Türkçe isimler oluşturmak için kütüphane
fake = Faker('tr_TR')

# Sabit Değişkenler
sigorta_turleri = ['Trafik (Tek Başına)', 'Trafik ve Kasko', 'DASK', 'Seyahat Sigortası']
satir_sayisi = 1000

data = []

for _ in range(satir_sayisi):
    # 1. İsim
    isim = fake.name()
    
    # 2. Sigorta Türü ve Mantıklı Fiyatlandırma
    sigorta_turu = random.choice(sigorta_turleri)
    
    if sigorta_turu == 'Trafik (Tek Başına)':
        police_degeri = random.randint(4000, 12000)
    elif sigorta_turu == 'Trafik ve Kasko':
        police_degeri = random.randint(15000, 50000)
    elif sigorta_turu == 'DASK':
        police_degeri = random.randint(500, 2000)
    else: # Seyahat
        police_degeri = random.randint(300, 2500)
        
    # 3. Komisyon (%10 ile %30 arası)
    komisyon_orani = random.randint(10, 30)
    komisyon_tutari = police_degeri * (komisyon_orani / 100)
    
    # 4. Tarih (Son 1 yıl içinden rastgele)
    gun_farki = random.randint(0, 365)
    tarih = datetime.now() - timedelta(days=gun_farki)
    tarih_str = tarih.strftime('%d.%m.%Y')
    
    # 5. Yenileme Yılı (0-10)
    yenileme = random.randint(0, 10)
    
    # 6. Referans (%30 ihtimalle referanslı, %70 referanssız)
    referans_var_mi = random.choices([True, False], weights=[30, 70])[0]
    referans = fake.name() if referans_var_mi else "Yok"

    # Listeye ekle
    data.append([
        isim, 
        sigorta_turu, 
        police_degeri, 
        komisyon_orani, 
        round(komisyon_tutari, 2), 
        tarih_str, 
        yenileme, 
        referans
    ])

# DataFrame oluşturma
df = pd.DataFrame(data, columns=[
    'İsim Soyisim', 
    'Sigorta Türü', 
    'Poliçe Değeri (TL)', 
    'Komisyon Oranı (%)', 
    'Komisyon Tutarı (TL)', 
    'Poliçe Kesim Tarihi', 
    'Yenileme Yılı', 
    'Referans'
])

# Excel'e kaydetme (veya csv)
df.to_excel('sigorta_musteri_listesi_1000.xlsx', index=False)
print("Dosya başarıyla oluşturuldu: sigorta_musteri_listesi_1000.xlsx")

# İlk 5 satırı ekrana bas
print(df.head())

In [34]:
!pip install faker

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import random
from faker import Faker
from datetime import datetime, timedelta

#.yama yaptım ve kendim için özelleştirdim.

# Türkçe isimler ve veriler oluşturmak için kütüphane
fake = Faker('tr_TR')

# --- Ön Hazırlık Listeleri (Yama ile gelen kısım) ---
# Rastgele 80 şehir seçip havuz oluşturuyoruz
sehir_listesi = [fake.city() for _ in range(80)]

# Rastgele 50 meslek seçip havuz oluşturuyoruz
meslek_listesi = [fake.job() for _ in range(50)]

# Sigorta Türleri Listesi
sigorta_turleri = ["Trafik", "Kasko", "Trafik ve Kasko", "Dask", "Konut", "Dask ve Konut"]

satir_sayisi = 1000
data = []


for _ in range(satir_sayisi):
    # 1. Kişisel Bilgiler (İsim, Şehir, Meslek)
    isim = fake.name()
    sehir = random.choice(sehir_listesi)
    meslek = random.choice(meslek_listesi)

    # 2. Sigorta Türü Seçimi
    sigorta_turu = random.choice(sigorta_turleri)

    # 3. Fiyatlandırma Mantığı (Yama ile güncellenen kısım)
    if sigorta_turu == "Trafik":
        police_degeri = random.randint(6000, 10000)
    elif sigorta_turu == "Kasko":
        police_degeri = random.randint(8000, 12000)
    elif sigorta_turu == "Trafik ve Kasko":
        police_degeri = random.randint(14000, 22000)
    elif sigorta_turu == "Dask":
        police_degeri = random.randint(5000, 7000)
    elif sigorta_turu == "Konut":
        police_degeri = random.randint(6000, 8000)
    elif sigorta_turu == "Dask ve Konut":
        police_degeri = random.randint(11000, 15000)
    else:
        police_degeri = 0 # Güvenlik amaçlı varsayılan

    # 4. Komisyon (%8 ile %20 arası)
    komisyon_orani = random.randint(8, 20)
    komisyon_tutari = police_degeri * (komisyon_orani / 100)

    # 5. Tarih (Son 1 yıl içinden rastgele - İlk koddan korundu)
    gun_farki = random.randint(0, 365)
    tarih = datetime.now() - timedelta(days=gun_farki)
    tarih_str = tarih.strftime('%d.%m.%Y')

    # 6. Yenileme Yılı (0-10 - İlk koddan korundu)
    yenileme = random.randint(0, 10)

    # 7. Referans (%30 ihtimalle - İlk koddan korundu)
    referans_var_mi = random.choices([True, False], weights=[30, 70])[0]
    referans = fake.name() if referans_var_mi else "Yok"

    # Listeye ekle
    data.append([
        isim,
        sehir,
        meslek,
        sigorta_turu,
        police_degeri,
        komisyon_orani,
        round(komisyon_tutari, 2),
        tarih_str,
        yenileme,
        referans
    ])

# DataFrame oluşturma
musteriList = pd.DataFrame(data, columns=[
    'İsim Soyisim',
    'Şehir',
    'Meslek',
    'Sigorta Türü',
    'Poliçe Değeri (TL)',
    'Komisyon Oranı (%)',
    'Komisyon Tutarı (TL)',
    'Poliçe Kesim Tarihi',
    'Yenileme Yılı',
    'Referans'
])

Requirement already satisfied: faker in /usr/local/lib/python3.12/dist-packages (38.2.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/dist-packages (from faker) (2025.2)

In [35]:
musteriList #. çalışma yapabilmek için oluşturulmuş veri seti.

,İsim Soyisim,Şehir,Meslek,Sigorta Türü,Poliçe Değeri (TL),Komisyon Oranı (%),Komisyon Tutarı (TL),Poliçe Kesim Tarihi,Yenileme Yılı,Referans
0,Akgüneş Öcalan Ergül,East Saygın,Ergonomist,Dask ve Konut,11581,17,1968.77,06.08.2025,2,Yok
1,Arş. Gör. Tule Musaffa Soylu,East Sadeti,Gündelikçi,Dask ve Konut,11467,10,1146.70,26.03.2025,4,Yok
2,Aliabbas Demirel,South Serdaland,Ergonomist,Konut,7223,15,1083.45,09.04.2025,0,Yok
3,Orgün Akçay,North Asım,Paralı asker,Konut,7303,8,584.24,16.12.2024,6,Nezihi Sezgin
4,Prof. Ildız Akçay Yılmaz,Port Çıdalchester,Satış elemanı,Trafik ve Kasko,14039,8,1123.12,19.03.2025,9,Yok
...,...,...,...,...,...,...,...,...,...,...
995,Üzer Soylu,Aranhaven,Belediye başkanı,Trafik,9425,19,1790.75,18.11.2025,7,Prof. Sakip Gülel Çetin
996,Akbaş Hançer,Yamanfort,Sünnetçi,Dask ve Konut,13623,17,2315.91,18.10.2025,8,Yok
997,Ümmühan Zorlu,Adıgünfort,Hayvan bakıcısı,Konut,6806,14,952.84,06.03.2025,7,Hacile Çorlu Alemdar
998,Av. Abdulgazi Nurkan Yaman,Durmuşberg,Operatör,Dask,5352,19,1016.88,28.04.2025,7,Hinet Demir Aksu
999,Yrd. Doç. Özdil Başhan Durdu,Türkstad,Tesgahtar,Trafik ve Kasko,17528,8,1402.24,27.11.2025,0,Müret Mecide Akça Demir

In [36]:
meslek_listesi

['Müfettiş',
 'Elektrik-Elektronik mühendisi',
 'Acentacı',
 'Klarnetçi',
 'Hayvan bakıcısı',
 'Gündelikçi',
 'Operatör',
 'Belediye başkanı',
 'Büyükelçi',
 'Kamarot',
 'Müze müdürü',
 'Host',
 'Sansürcü',
 'Oyun yazarı',
 'Botanikçi',
 'Finansör',
 'Komisyoncu',
 'Çorapçı',
 'Astrolog',
 'Çöp işçisi',
 'Fon yöneticisi',
 'Meteoroloji uzmanı',
 'Rektör',
 'Uzman Jandarma',
 'Ergonomist',
 'Sünnetçi',
 'Gelir uzman yardımcısı',
 'Kasap',
 'Tesgahtar',
 'Finansör',
 'Heykeltıraş',
 'Öğretmen',
 'Manifaturacı',
 'Gümrük memuru',
 'Saat tamircisi',
 'Çatıcı',
 'Tarım işçisi',
 'Dilenci',
 'Obuacı',
 'Piyango satıcısı',
 'Satış elemanı',
 'Palyaço',
 'Siyasetçi',
 'Demirci',
 'Paralı asker',
 'Tarihçi',
 'Gelir uzman yardımcısı',
 'Animatör',
 'Koruma görevlisi',
 'Kırtasiyeci']

In [37]:
musteriList = musteriList.sort_values(by='Poliçe Kesim Tarihi', ascending=False) 
#. veri seti dağınık olduğu için önce tarihlre göre sıraladım.

In [38]:
musteriList

,İsim Soyisim,Şehir,Meslek,Sigorta Türü,Poliçe Değeri (TL),Komisyon Oranı (%),Komisyon Tutarı (TL),Poliçe Kesim Tarihi,Yenileme Yılı,Referans
802,Harbinaz Korutürk Akça,Yıldırımstad,Meteoroloji uzmanı,Trafik ve Kasko,20335,9,1830.15,31.12.2024,5,Kiyasi Günser Arslan
757,Fazul Akatay Bilge,East Saygın,Botanikçi,Trafik ve Kasko,14623,18,2632.14,31.12.2024,10,Yok
877,Bay Okseven Emin Korutürk,Port İsakhaven,Tesgahtar,Trafik,6644,12,797.28,31.12.2024,7,Yok
167,Aykutalp Akdeniz,Port Çıdalchester,Fon yöneticisi,Trafik,6388,10,638.80,31.12.2024,2,Emiş Şama İnönü
626,Esna Çetin,Arslanmouth,Tarım işçisi,Dask ve Konut,11915,17,2025.55,31.12.2024,7,Abdulgazi Alparslan Soylu Akdeniz
...,...,...,...,...,...,...,...,...,...,...
536,Elnur Nazlim Bilge,Işınton,Astrolog,Dask,6016,16,962.56,01.02.2025,10,Yok
867,Hüda Tarhan Akar,Akçabayburgh,Host,Dask ve Konut,12452,20,2490.40,01.02.2025,5,Doç. Işıkay Halidun Yaman
306,Öğr. Gülseren Sevsevil Güçlü,Arslanland,Oyun yazarı,Dask,6592,17,1120.64,01.01.2025,5,Gürelcem Çorlu
817,Deviner Ensari Ergül Aslan,Tarhanstad,Komisyoncu,Trafik,6706,19,1274.14,01.01.2025,6,Yok
133,Soyselçuk Akar,Güçalton,Sünnetçi,Dask,6079,15,911.85,01.01.2025,6,Akboğa Şensoy

In [39]:
musteriList['Poliçe Kesim Tarihi'] = pd.to_datetime(musteriList['Poliçe Kesim Tarihi'], format='%d.%m.%Y', errors='coerce') 
#. Poliçe kesim tarihini sıralayabilemk için string'den datetime'a çeviriyoruz.

In [40]:
musteriList['Ay'] = musteriList['Poliçe Kesim Tarihi'].dt.month_name()
#.

In [41]:
musteriList

,İsim Soyisim,Şehir,Meslek,Sigorta Türü,Poliçe Değeri (TL),Komisyon Oranı (%),Komisyon Tutarı (TL),Poliçe Kesim Tarihi,Yenileme Yılı,Referans,Ay
802,Harbinaz Korutürk Akça,Yıldırımstad,Meteoroloji uzmanı,Trafik ve Kasko,20335,9,1830.15,2024-12-31,5,Kiyasi Günser Arslan,December
757,Fazul Akatay Bilge,East Saygın,Botanikçi,Trafik ve Kasko,14623,18,2632.14,2024-12-31,10,Yok,December
877,Bay Okseven Emin Korutürk,Port İsakhaven,Tesgahtar,Trafik,6644,12,797.28,2024-12-31,7,Yok,December
167,Aykutalp Akdeniz,Port Çıdalchester,Fon yöneticisi,Trafik,6388,10,638.80,2024-12-31,2,Emiş Şama İnönü,December
626,Esna Çetin,Arslanmouth,Tarım işçisi,Dask ve Konut,11915,17,2025.55,2024-12-31,7,Abdulgazi Alparslan Soylu Akdeniz,December
...,...,...,...,...,...,...,...,...,...,...,...
536,Elnur Nazlim Bilge,Işınton,Astrolog,Dask,6016,16,962.56,2025-02-01,10,Yok,February
867,Hüda Tarhan Akar,Akçabayburgh,Host,Dask ve Konut,12452,20,2490.40,2025-02-01,5,Doç. Işıkay Halidun Yaman,February
306,Öğr. Gülseren Sevsevil Güçlü,Arslanland,Oyun yazarı,Dask,6592,17,1120.64,2025-01-01,5,Gürelcem Çorlu,January
817,Deviner Ensari Ergül Aslan,Tarhanstad,Komisyoncu,Trafik,6706,19,1274.14,2025-01-01,6,Yok,January
133,Soyselçuk Akar,Güçalton,Sünnetçi,Dask,6079,15,911.85,2025-01-01,6,Akboğa Şensoy,January

In [42]:
aralık = musteriList[musteriList['Ay'] == "December"]

In [43]:
aralık #.aralık ayında olanlar 2025 ve 2024 olarak ayrılmamsı gerekiyor.

,İsim Soyisim,Şehir,Meslek,Sigorta Türü,Poliçe Değeri (TL),Komisyon Oranı (%),Komisyon Tutarı (TL),Poliçe Kesim Tarihi,Yenileme Yılı,Referans,Ay
802,Harbinaz Korutürk Akça,Yıldırımstad,Meteoroloji uzmanı,Trafik ve Kasko,20335,9,1830.15,2024-12-31,5,Kiyasi Günser Arslan,December
757,Fazul Akatay Bilge,East Saygın,Botanikçi,Trafik ve Kasko,14623,18,2632.14,2024-12-31,10,Yok,December
877,Bay Okseven Emin Korutürk,Port İsakhaven,Tesgahtar,Trafik,6644,12,797.28,2024-12-31,7,Yok,December
167,Aykutalp Akdeniz,Port Çıdalchester,Fon yöneticisi,Trafik,6388,10,638.80,2024-12-31,2,Emiş Şama İnönü,December
626,Esna Çetin,Arslanmouth,Tarım işçisi,Dask ve Konut,11915,17,2025.55,2024-12-31,7,Abdulgazi Alparslan Soylu Akdeniz,December
...,...,...,...,...,...,...,...,...,...,...,...
916,Prof. Sencar Ülker,Ergülbury,Acentacı,Trafik ve Kasko,21669,13,2816.97,2025-12-01,7,Yok,December
803,Öğr. Durdali Tekiner Akçay,Durmuşberg,Çatıcı,Dask,5777,8,462.16,2025-12-01,1,Yok,December
640,Eşref Fırat,Necvachester,Animatör,Trafik,7707,18,1387.26,2025-12-01,2,İmrihan Aslan,December
600,Masume Akgündüz,North Asım,Müze müdürü,Trafik,6485,9,583.65,2025-12-01,3,Öğr. Nebih Eraslan,December
361,Süheyda Siti Ülker,Avunçland,Kırtasiyeci,Kasko,10846,10,1084.60,2025-12-01,2,Yok,December

In [44]:
AralıkListesi = musteriList[musteriList['Ay'] == "December"]

In [45]:
AralıkListesi

,İsim Soyisim,Şehir,Meslek,Sigorta Türü,Poliçe Değeri (TL),Komisyon Oranı (%),Komisyon Tutarı (TL),Poliçe Kesim Tarihi,Yenileme Yılı,Referans,Ay
802,Harbinaz Korutürk Akça,Yıldırımstad,Meteoroloji uzmanı,Trafik ve Kasko,20335,9,1830.15,2024-12-31,5,Kiyasi Günser Arslan,December
757,Fazul Akatay Bilge,East Saygın,Botanikçi,Trafik ve Kasko,14623,18,2632.14,2024-12-31,10,Yok,December
877,Bay Okseven Emin Korutürk,Port İsakhaven,Tesgahtar,Trafik,6644,12,797.28,2024-12-31,7,Yok,December
167,Aykutalp Akdeniz,Port Çıdalchester,Fon yöneticisi,Trafik,6388,10,638.80,2024-12-31,2,Emiş Şama İnönü,December
626,Esna Çetin,Arslanmouth,Tarım işçisi,Dask ve Konut,11915,17,2025.55,2024-12-31,7,Abdulgazi Alparslan Soylu Akdeniz,December
...,...,...,...,...,...,...,...,...,...,...,...
916,Prof. Sencar Ülker,Ergülbury,Acentacı,Trafik ve Kasko,21669,13,2816.97,2025-12-01,7,Yok,December
803,Öğr. Durdali Tekiner Akçay,Durmuşberg,Çatıcı,Dask,5777,8,462.16,2025-12-01,1,Yok,December
640,Eşref Fırat,Necvachester,Animatör,Trafik,7707,18,1387.26,2025-12-01,2,İmrihan Aslan,December
600,Masume Akgündüz,North Asım,Müze müdürü,Trafik,6485,9,583.65,2025-12-01,3,Öğr. Nebih Eraslan,December
361,Süheyda Siti Ülker,Avunçland,Kırtasiyeci,Kasko,10846,10,1084.60,2025-12-01,2,Yok,December

In [46]:
ocakListesi = musteriList[musteriList['Ay'] == "January"]

In [47]:
ocakListesi

,İsim Soyisim,Şehir,Meslek,Sigorta Türü,Poliçe Değeri (TL),Komisyon Oranı (%),Komisyon Tutarı (TL),Poliçe Kesim Tarihi,Yenileme Yılı,Referans,Ay
204,Güldam Manço,Lake Tagangül,Çöp işçisi,Dask,6042,11,664.62,2025-01-31,1,Güçal Aslan,January
257,Feden Seven Zengin,South Çopur,Fon yöneticisi,Dask,6511,10,651.10,2025-01-30,4,Yok,January
586,Çev. Zubeyde Bilge Şama,Durmuşberg,Manifaturacı,Kasko,10610,13,1379.30,2025-01-30,4,Yok,January
772,Yrd. Doç. Cuheyna Aybet Ergül Hayrioğlu,Sezginport,Koruma görevlisi,Konut,7796,8,623.68,2025-01-30,6,Yok,January
966,Begim Eraslan,Ülkerview,Satış elemanı,Dask ve Konut,12688,19,2410.72,2025-01-30,9,Yok,January
...,...,...,...,...,...,...,...,...,...,...,...
811,Öğr. Kutay Cindoruk Durdu,East Arkut,Sünnetçi,Dask ve Konut,11454,13,1489.02,2025-01-03,10,Hudavent Berki Demir,January
579,Teber Ökkaş Türk,Akçabayburgh,Fon yöneticisi,Trafik,8548,16,1367.68,2025-01-02,6,Jankat Kavurt Dumanlı,January
306,Öğr. Gülseren Sevsevil Güçlü,Arslanland,Oyun yazarı,Dask,6592,17,1120.64,2025-01-01,5,Gürelcem Çorlu,January
817,Deviner Ensari Ergül Aslan,Tarhanstad,Komisyoncu,Trafik,6706,19,1274.14,2025-01-01,6,Yok,January
133,Soyselçuk Akar,Güçalton,Sünnetçi,Dask,6079,15,911.85,2025-01-01,6,Akboğa Şensoy,January

In [48]:
ocakListesi= ocakListesi.sort_values(by="Sigorta Türü", ascending=False) #.sigorta türüne göre dizdim.

In [49]:
ocakListesi

,İsim Soyisim,Şehir,Meslek,Sigorta Türü,Poliçe Değeri (TL),Komisyon Oranı (%),Komisyon Tutarı (TL),Poliçe Kesim Tarihi,Yenileme Yılı,Referans,Ay
23,Zennun Durmuş,Port Tanbayland,Elektrik-Elektronik mühendisi,Trafik ve Kasko,15309,15,2296.35,2025-01-15,10,Çev. Gülsalın Duran Durmuş,January
268,Ümray Çamurcuoğlu Bilge,North Asım,Gelir uzman yardımcısı,Trafik ve Kasko,14352,16,2296.32,2025-01-26,9,Yok,January
642,Süsen Altınbike Sezgin Durmuş,Türkstad,Satış elemanı,Trafik ve Kasko,20279,15,3041.85,2025-01-08,6,Yok,January
85,Yrd. Doç. Erdemer Çorlu,Demirburgh,Büyükelçi,Trafik ve Kasko,19626,18,3532.68,2025-01-20,2,Gülkadın Sidar Fırat,January
55,Çev. Akgüneş Zubeyde Şafak Aksu,Yıldırımstad,Tarım işçisi,Trafik ve Kasko,16219,15,2432.85,2025-01-19,9,Yok,January
...,...,...,...,...,...,...,...,...,...,...,...
249,Sağcan Ergül,Port Zeynelabidin,Tarihçi,Dask,6030,17,1025.10,2025-01-21,3,Yok,January
449,Eskinalp Dorukhan Tevetoğlu Akça,Port İsakhaven,Belediye başkanı,Dask,5236,18,942.48,2025-01-22,9,Mihin Tecimer Gül,January
460,Torhan Yaman,South Serdaland,Finansör,Dask,6907,14,966.98,2025-01-25,7,Yok,January
547,Dr. Sargın Tolonbay Yorulmaz,West Akkerman,Acentacı,Dask,5159,17,877.03,2025-01-28,5,Yok,January
133,Soyselçuk Akar,Güçalton,Sünnetçi,Dask,6079,15,911.85,2025-01-01,6,Akboğa Şensoy,January

In [50]:
print(f"Ocak ayı kayıt sayısı: {len(ocakListesi)}")
ocakListesi.head()

Ocak ayı kayıt sayısı: 80

,İsim Soyisim,Şehir,Meslek,Sigorta Türü,Poliçe Değeri (TL),Komisyon Oranı (%),Komisyon Tutarı (TL),Poliçe Kesim Tarihi,Yenileme Yılı,Referans,Ay
23,Zennun Durmuş,Port Tanbayland,Elektrik-Elektronik mühendisi,Trafik ve Kasko,15309,15,2296.35,2025-01-15,10,Çev. Gülsalın Duran Durmuş,January
268,Ümray Çamurcuoğlu Bilge,North Asım,Gelir uzman yardımcısı,Trafik ve Kasko,14352,16,2296.32,2025-01-26,9,Yok,January
642,Süsen Altınbike Sezgin Durmuş,Türkstad,Satış elemanı,Trafik ve Kasko,20279,15,3041.85,2025-01-08,6,Yok,January
85,Yrd. Doç. Erdemer Çorlu,Demirburgh,Büyükelçi,Trafik ve Kasko,19626,18,3532.68,2025-01-20,2,Gülkadın Sidar Fırat,January
55,Çev. Akgüneş Zubeyde Şafak Aksu,Yıldırımstad,Tarım işçisi,Trafik ve Kasko,16219,15,2432.85,2025-01-19,9,Yok,January

In [51]:
input_sutunlar = ['Meslek', 'Sigorta Türü', 'Şehir', 'Yenileme Yılı', 'Referans']
X_ham =ocakListesi [input_sutunlar]
y =ocakListesi ['Poliçe Değeri (TL)']
X = pd.get_dummies(X_ham, drop_first=True)
print("İşlem tamam!")
print(f"Orijinal sütun sayısı: {len(input_sutunlar)}")
print(f"Yeni (sayısallaştırılmış) sütun sayısı: {X.shape[1]}")

İşlem tamam!
Orijinal sütun sayısı: 5
Yeni (sayısallaştırılmış) sütun sayısı: 124

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# 1. Eğitim ve Test setlerini ayıralım
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Modeli kuralım (Random Forest)
model = RandomForestRegressor(n_estimators=100, random_state=42)

# 3. Modeli eğitelim
model.fit(X_train, y_train)

# 4. Test edelim (Hata payına bakalım)
tahminler = model.predict(X_test)
hata_payi = mean_absolute_error(y_test, tahminler)

print(f"Model Eğitildi!")
print(f"Ortalama Hata Payı (MAE): {hata_payi:.2f} TL")

Model Eğitildi!
Ortalama Hata Payı (MAE): 975.15 TL

In [55]:
# 1. Tüm Ocak verisi için tahmin yapalım
ocak_tahminleri = model.predict(X)

# 2. Tahminleri ana tabloya ekleyelim
# Uyarı almamak için .copy() ile çalışıyoruz
ocak_verileri_son = ocakListesi.copy()
ocak_verileri_son['Tahmini Değer'] = ocak_tahminleri

# 3. 'Tahmini Değer'e göre büyükten küçüğe sıralayalım
oncelikli_musteriler = ocak_verileri_son.sort_values(by='Tahmini Değer', ascending=False)

# 4. İlk 10 müşteriyi gösterelim
sutunlar = ['İsim Soyisim', 'Meslek', 'Sigorta Türü', 'Poliçe Değeri (TL)', 'Tahmini Değer']
oncelikli_musteriler[sutunlar].head(79)

,İsim Soyisim,Meslek,Sigorta Türü,Poliçe Değeri (TL),Tahmini Değer
9,Server Tarhan,Tesgahtar,Trafik ve Kasko,21697,20939.52
43,Müfit Sezer,Saat tamircisi,Trafik ve Kasko,21288,20801.03
497,Öğr. Merba Hayrioğlu Sakarya,Operatör,Trafik ve Kasko,18035,20685.04
531,Öğr. Vefia Manço İhsanoğlu,Host,Trafik ve Kasko,21458,20676.53
544,Musafet Atılgan Erdoğan,Acentacı,Trafik ve Kasko,19744,20153.66
...,...,...,...,...,...
657,Soykut Aksu,Heykeltıraş,Dask,5707,5624.42
547,Dr. Sargın Tolonbay Yorulmaz,Acentacı,Dask,5159,5590.63
17,Sezen Mehdiye Akar,Çöp işçisi,Dask,5797,5461.04
789,Evde Manço,Paralı asker,Dask,5348,5406.51
248,Uz. Teknaz Selmin Akdeniz,Botanikçi,Dask,5393,5399.93